pipeline{
    agent any
    stages{
        stage("unit testing patient project"){
            steps{
                dir("build_java"){
                    bat "mvn clean compile test --fail-never"
                }
            }
        }
        
    }
    post {
        always {
            junit(testResults: '**/test-results/*.xml', allowEmptyResults : true)
        }
    }
}
