pipeline {
    agent any

        stages {
 
            stage ('test') {
                steps {
                  dir("build_java"){
                        bar "mvn clean compile test"
                  }           
                   
                }
            }
        }
}
